# docker-compose.yml
version: '3.8'

services:
  esp-idf:
    build:
      context: .
      dockerfile: Dockerfile
    image: esp-idf
    volumes:
      -  ${PROJECT_PATH:-./project}:/project
    working_dir: /project
    environment:
      - IDF_TOOLS_PATH=/opt/esp/tools
    stdin_open: true
    tty: true
    command: idf.py build

   # Development service with interactive shell
  esp-idf-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: esp-idf-dev
    volumes:
      - ${PROJECT_PATH:-./project}:/project
      - /dev:/dev
    device_cgroup_rules:
      - 'c 166:* rmw'   # 166 is the character device major number for /dev/ttyACM*
      - 'c 188:* rmw'   # 188 is the character device major number for /dev/ttyUSB*
    working_dir: /project
    stdin_open: true
    tty: true
    environment:
      - HOME=/home/esp
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8

  # Flash service (with USB access)
  esp-idf-flash:
    build:
      context: .
      dockerfile: Dockerfile
    image: esp-idf-flash
    volumes:
      - ./project:/project
      - /dev:/dev
    privileged: true
    working_dir: /project
    environment:
      - IDF_TOOLS_PATH=/opt/esp/tools
      - ESPPORT=/dev/ttyUSB0
    stdin_open: true
    tty: true
    command: idf.py -p /dev/ttyUSB0 flash

  esp-idf-arduino:
    build:
      context: .
      dockerfile: darduino/Dockerfile
    image: esp-idf-arduino
    network_mode: "host"
    environment:
      - "DISPLAY=${DISPLAY}"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "${HOME}/topics:/topics"
      - ${PWD}/Arduino:/home/developer/Arduino/projects
    command: "arduino-ide"
    privileged: true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

volumes:
  esp-tools: